# Generated by Django 4.0.6 on 2022-07-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('start_price', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('current_bid_user_id', models.IntegerField(blank=True)),
                ('current_bid_price', models.IntegerField(blank=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('winner_user_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
