# Generated by Django 4.0.6 on 2022-07-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_bid_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
