# Generated by Django 4.0.6 on 2022-07-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_auction_current_bid_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_bid_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
